import type { Catalog } from "./types";
import { validateCatalog } from "./domain";
export function seedCatalog(): Catalog {
  return validateCatalog({
    version: 1,
    updatedAt: "2026-10-03T08:00:00Z",
    ingredients: [
      {
        id: "rosetta",
        name: "Pane rosetta",
        unit: "pz",
        stock: 80,
        minStock: 20,
        packSize: 10,
        allergens: ["glutine"],
        vegan: true,
      },
      {
        id: "provola",
        name: "Provola",
        unit: "g",
        stock: 1100,
        minStock: 500,
        packSize: 1000,
        allergens: ["latte"],
        vegan: false,
      },
      {
        id: "pomodoro",
        name: "Pomodoro",
        unit: "g",
        stock: 2200,
        minStock: 500,
        packSize: 1000,
        allergens: [],
        vegan: true,
      },
      {
        id: "focaccia",
        name: "Focaccia all’olio",
        unit: "pz",
        stock: 40,
        minStock: 10,
        packSize: 10,
        allergens: ["glutine"],
        vegan: true,
      },
      {
        id: "cotto",
        name: "Prosciutto cotto",
        unit: "g",
        stock: 1800,
        minStock: 500,
        packSize: 500,
        allergens: [],
        vegan: false,
      },
      {
        id: "hummus",
        name: "Hummus di ceci",
        unit: "g",
        stock: 1800,
        minStock: 400,
        packSize: 500,
        allergens: ["sesamo"],
        vegan: true,
      },
      {
        id: "verdure",
        name: "Verdure grigliate",
        unit: "g",
        stock: 2400,
        minStock: 500,
        packSize: 1000,
        allergens: [],
        vegan: true,
      },
      {
        id: "ciambella",
        name: "Ciambella",
        unit: "pz",
        stock: 35,
        minStock: 10,
        packSize: 5,
        allergens: ["glutine", "uova", "latte"],
        vegan: false,
      },
      {
        id: "te",
        name: "Tè al limone 33 cl",
        unit: "pz",
        stock: 60,
        minStock: 12,
        packSize: 24,
        allergens: [],
        vegan: true,
      },
      {
        id: "succo",
        name: "Succo di pesca 20 cl",
        unit: "pz",
        stock: 48,
        minStock: 12,
        packSize: 24,
        allergens: [],
        vegan: true,
      },
    ],
    products: [
      {
        id: "caprese",
        name: "La Caprese",
        category: "Panini",
        description: "Rosetta, provola e pomodoro. La pausa che sa di buono.",
        priceCents: 280,
        dailyLimit: 80,
        active: true,
        vegan: false,
        allergens: [],
        traces: [],
        image: "caprese",
        recipe: [
          { ingredientId: "rosetta", quantity: 1 },
          { ingredientId: "provola", quantity: 50 },
          { ingredientId: "pomodoro", quantity: 50 },
        ],
      },
      {
        id: "focaccia-cotto",
        name: "Focaccia & cotto",
        category: "Focacce",
        description: "Focaccia all’olio con prosciutto cotto e provola.",
        priceCents: 320,
        dailyLimit: 40,
        active: true,
        vegan: false,
        allergens: [],
        traces: [],
        image: "focaccia",
        recipe: [
          { ingredientId: "focaccia", quantity: 1 },
          { ingredientId: "cotto", quantity: 60 },
          { ingredientId: "provola", quantity: 40 },
        ],
      },
      {
        id: "orto",
        name: "L’Orto in un panino",
        category: "Panini",
        description: "Hummus di ceci e verdure grigliate in una rosetta.",
        priceCents: 300,
        dailyLimit: 35,
        active: true,
        vegan: true,
        allergens: [],
        traces: [],
        image: "vegano",
        recipe: [
          { ingredientId: "rosetta", quantity: 1 },
          { ingredientId: "hummus", quantity: 50 },
          { ingredientId: "verdure", quantity: 70 },
        ],
      },
      {
        id: "ciambella",
        name: "Una dolce pausa",
        category: "Dolci",
        description: "Ciambella soffice con una spolverata di zucchero.",
        priceCents: 150,
        dailyLimit: 35,
        active: true,
        vegan: false,
        allergens: [],
        traces: ["frutta a guscio"],
        image: "dolce",
        recipe: [{ ingredientId: "ciambella", quantity: 1 }],
      },
      {
        id: "te-limone",
        name: "Tè al limone",
        category: "Bevande",
        description: "Tè freddo al limone, lattina da 33 cl.",
        priceCents: 150,
        dailyLimit: 60,
        active: true,
        vegan: true,
        allergens: [],
        traces: [],
        image: "te",
        recipe: [{ ingredientId: "te", quantity: 1 }],
      },
      {
        id: "succo-pesca",
        name: "Succo di pesca",
        category: "Bevande",
        description: "Succo di frutta alla pesca, confezione da 20 cl.",
        priceCents: 130,
        dailyLimit: 48,
        active: true,
        vegan: true,
        allergens: [],
        traces: [],
        image: "succo",
        recipe: [{ ingredientId: "succo", quantity: 1 }],
      },
    ],
  });
}
